export const INIT_STATEMENTS = 'INIT_STATEMENTS'
export const INIT_INDEX = 'INIT_INDEX'
export const INIT_STATEMENT = 'INIT_STATEMENT'
export const SET__COMMENTS = 'SET__COMMENTS'
export const INIT_HOT_STATEMENTS = 'INIT_HOT_STATEMENTS'

export const ADD_LIKE_S = 'ADD_LIKE_S'
export const DELETE_LIKE_S = 'DELETE_LIKE_S'

export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_COUNT = 'ADD_COMMENT_COUNT'
export const DECLARE_COMMENT_COUNT = 'DECLARE_COMMENT_COUNT'

export const INIT_COMMENT_PROFILE = 'INIT_COMMENT_PROFILE'
export const INIT_COMMENT_INDEX = 'INIT_COMMENT_INDEX'

export const DELETE_LIKE_C = 'DELETE_LIKE_C'
export const ADD_LIKE_C = 'ADD_LIKE_C'

export const INIT_PROFILE = 'INIT_PROFILE'

export const INIT_POSTED = 'INIT_POSTED'
export const INIT_COMMENTED = 'INIT_COMMENTED'
export const INIT_LIKED = 'INIT_LIKED'

export const INIT_TYPE = 'INIT_TYPE'

export const INIT_COUNT = 'INIT_COUNT'
export const RESET_COUNT = 'RESET_COUNT'

export const INIT_NOTICES = 'INIT_NOTICES'

export const SET_COMMENT_SELF = 'SET_COMMENT_SELF'

export const ADD_STATEMENT = 'ADD_STATEMENT'
export const INIT_STATEMENT_PROFILE = 'INIT_STATEMENT_PROFILE'

export const INIT_LIKE_INDEX = 'INIT_LIKE_INDEX'
export const REMOVE_LIKED = 'REMOVE_LIKED'
export const DECLARE_LIKED_COUNT = 'CHANGE_LIKED_COUNT'

export const REMOVE_COMMENTED = 'REMOVE_COMMENTED'
export const DECLARE_COMMENTED_COUNT = 'DECLARE_COMMENTED_COUNT'

export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_STATEMENT = 'DELETE_STATEMENT'

export const UPDATE_COMMENT_LOADING = 'UPDATE_COMMENT_LOADING'
export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING'
export const UPDATE_LOADING = 'UPDATE_LOADING'
export const UPDATE_REFRESH = 'UPDATE_REFRESH'
export const UPDATE_LOADED_ALL = 'UPDATE_LOADED_ALL'

export const INIT_POPUP = 'INIT_POPUP'
export const SHOW_CENTER_POPUP = 'SHOW_CENTER_POPUP'
export const SHOW_TOP_POPUP = 'SHOW_TOP_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'

export const PUBLISHING = 'PUBLISHING'
export const UPDATE_LOGIN_LOADING = 'UPDATE_LOGIN_LOADING'

export const INIT_CARDS = 'INIT_CARDS'
export const ADD_CARD = 'ADD_CARD'
export const INIT_CARD_INDEX = 'INIT_CARD_INDEX'
export const DELETE_CARD = 'DELETE_CARD'

